coverage:
  range: "85...100"

  status:
    project:
      default:
        target: 95
        threshold: 0%

    patch:
      default:
        target: 90
        threshold: 0%
        only_pulls: true
