language: python
dist: xenial

python:
  - 3.8
  - 3.9
  - 3.10.0

install:
  - pip install -r ./requirements-dev.txt
  - pip install .

script:
  - flake8
  - mypy dlpfs tests
  - pytest

matrix:
  include:
  - python: 3.9
    script:
    - flake8
    - mypy dlpfs tests
    - pytest --cov-report=xml --cov=dlpfs --cov-append

